In [ ]:
pip install opencv-python

In [3]:
import cv2
col_img=cv2.imread("Images/lena_color.tiff")
gray_img=cv2.imread("Images/lena.jpg", cv2.IMREAD_GRAYSCALE)
print(gray_img)

[[162 164 160 ... 168 156 128]
 [161 163 160 ... 170 156 127]
 [161 163 161 ... 174 157 127]
 ...
 [ 42  44  52 ... 103 103 100]
 [ 44  46  54 ... 105 105 107]
 [ 44  46  53 ... 104 103 110]]


In [9]:
import cv2
import numpy as np
gray_img=cv2.imread("Images/lena.jpg", cv2.IMREAD_GRAYSCALE)
print(gray_img[0])
len(gray_img[0])

[162 164 160 162 163 156 164 161 165 162 163 161 155 164 160 157 159 155
 162 161 154 157 157 156 155 156 154 153 155 155 154 155 155 155 157 159
 160 166 161 165 166 164 166 174 169 175 174 169 171 174 166 176 166 169
 161 161 148 148 154 140 130 119 118 105  96  99  95  91  88  99 101  96
 103 100 103 104 105 106 104 109 110 107 108 106 105 109 109 109 107 108
 107 108 110 109 108 109 107 111 108 109 104 107 105 109 110 111 118 110
 111 118 123 118 112 123 121 121 126 122 121 124 123 129 129 123 122 129
 133 131 132 127 137 129 127 133 131 125 134 138 132 133 131 130 129 129
 132 126 129 124 135 128 128 131 127 132 126 127 135 131 136 133 128 133
 129 137 131 134 133 136 134 135 132 137 134 133 133 133 135 133 133 134
 133 132 131 132 132 135 138 136 131 131 133 132 134 136 131 134 138 137
 132 139 136 134 134 136 136 134 133 133 139 133 132 138 134 131 129 132
 132 127 130 132 133 131 128 132 131 128 135 134 131 134 131 133 131 133
 132 133 129 131 131 132 139 132 133 135 131 135 13

512

In [10]:
print(gray_img[0:10,0:10])

[[162 164 160 162 163 156 164 161 165 162]
 [161 163 160 162 163 157 163 161 165 161]
 [161 163 161 162 163 157 163 160 165 162]
 [162 163 162 161 162 157 162 161 165 162]
 [163 163 162 159 161 158 162 161 164 162]
 [163 161 161 158 160 159 161 160 161 160]
 [162 159 160 156 160 159 159 157 160 160]
 [160 158 160 156 160 159 158 155 161 162]
 [154 156 157 158 159 159 158 157 163 156]
 [157 156 156 156 156 156 156 156 161 154]]


In [11]:
print(gray_img.shape)
print(gray_img.dtype)

(512, 512)
uint8


In [ ]:
import cv2
gray_img=cv2.imread("Images/lena.jpg",cv2.IMREAD_GRAYSCALE)
cv2.imshow("lena images",gray_img)
cv2.waitkey()
cv2.destroyAllWindows()